// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDatabase.Models;

namespace MovieDatabase.Migrations
{
    [DbContext(typeof(EnterMovieContext))]
    [Migration("20230213153630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MovieDatabase.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            Director = "Joseph Kosinski",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Top Gun: Maverick",
                            Year = 2022
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Mystery/Comedy",
                            Director = "Rian Johnson",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Glass Onion",
                            Year = 2022
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Comedy/Drama",
                            Director = "Marc Forster",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "A Man Called Otto",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
